### ISSUE TITLE
Connection events are not stable

### ISSUE THREAD

**Issue by hasancaktar** [zhuovi/XiaoFeng#8] opened 2023-02-08 22:47 UTC
When we immediately connect and disconnect to the server, it cant consistently control the situation. It cant handle it. 
As you can see in the file, when a client connect the server and instantly disconnect, server cant understand it fast enough and it sometimes cant see the disconnection and add one client. As you wish, you can try it yourself and see what happens too (client list will be increase in number) . Can you fix this problem please?

![w](https://user-images.githubusercontent.com/53625738/217668299-3e7a0fcd-fdfd-40b9-be08-466b99bbf940.png)

**Comment by zhuovi** [comment] 2023-02-09 01:55
> 

把你list这个类型换成 System.Collections.Concurrent.ConcurrentBag<XiaoFeng.Net.IServerSession> 这个类型试一下，或者直接用 server.ConnectionSocketList 这个内置列表

**Comment by hasancaktar** [comment] 2023-02-10 06:50
While leaving the server open and sending messages to the clients, after a while the server stops and gives the error in the picture in the log folder.

![s](https://user-images.githubusercontent.com/53625738/218022332-b607034e-77d4-4eb1-9193-c43e5d9b22a9.png)

**Comment by zhuovi** [comment] 2023-02-10 06:56
> 

This error prompt is caused by the disconnection of the client and the failure to receive the message, but it will not affect the server to stop working

**Comment by hasancaktar** [comment] 2023-02-10 07:03
The server stops sending messages after a while while sending a message. New connections can be made. there is no problem with that. but the server is not sending messages. My guess is that the onMessage event is not triggered after a while. In my tests, the server was able to send messages to the clients for a maximum of 1 hour. Can we solve this problem please.

**Comment by zhuovi** [comment] 2023-02-10 07:06
> The server stops sending messages after a while while sending a message. New connections can be made. there is no problem with that. but the server is not sending messages. My guess is that the onMessage event is not triggered after a while. In my tests, the server was able to send messages to the clients for a maximum of 1 hour. Can we solve this problem please.

I haven't met the situation you said for an hour and it's over. Can you add QQ, my QQ: 7092734, so I can understand our real needs.

**Comment by hasancaktar** [comment] 2023-02-10 07:11
> > The server stops sending messages after a while while sending a message. New connections can be made. there is no problem with that. but the server is not sending messages. My guess is that the onMessage event is not triggered after a while. In my tests, the server was able to send messages to the clients for a maximum of 1 hour. Can we solve this problem please.
> 
> I haven't met the situation you said for an hour and it's over. Can you add QQ, my QQ: 7092734, so I can understand our real needs.

I couldn't use it because qq is in chinese. Are you using any other app?

**Comment by zhuovi** [comment] 2023-02-10 07:16
> > > The server stops sending messages after a while while sending a message. New connections can be made. there is no problem with that. but the server is not sending messages. My guess is that the onMessage event is not triggered after a while. In my tests, the server was able to send messages to the clients for a maximum of 1 hour. Can we solve this problem please.
> > 
> > 
> > I haven't met the situation you said for an hour and it's over. Can you add QQ, my QQ: 7092734, so I can understand our real needs.
> 
> I couldn't use it because qq is in chinese. Are you using any other app?

Can you send your test code? Is your server sending messages for push? Always send messages to clients in a loop?

**Comment by hasancaktar** [comment] 2023-02-10 07:20
> > > > The server stops sending messages after a while while sending a message. New connections can be made. there is no problem with that. but the server is not sending messages. My guess is that the onMessage event is not triggered after a while. In my tests, the server was able to send messages to the clients for a maximum of 1 hour. Can we solve this problem please.
> > > 
> > > 
> > > I haven't met the situation you said for an hour and it's over. Can you add QQ, my QQ: 7092734, so I can understand our real needs.
> > 
> > 
> > I couldn't use it because qq is in chinese. Are you using any other app?
> 
> Can you send your test code? Is your server sending messages for push? Always send messages to clients in a loop?

https://paste.ofcode.org/39jyKKFD9rpCgxS9vwsX8hn

**Comment by zhuovi** [comment] 2023-02-10 07:31
foreach (var client in clients.ToList())
{
client.Send(lastest_BID_USDTRY);
}
It should be that the service is stopped. Please change it to server. Send (last_BID_USDTRY); The server variable is the new NetServer<>object

**Comment by hasancaktar** [comment] 2023-02-10 07:37
> foreach (var client in clients.ToList()) { client.Send(lastest_BID_USDTRY); } It should be that the service is stopped. Please change it to server. Send (last_BID_USDTRY); The server variable is the new NetServer<>object

But I will not send it to all clients later on. I will send it to certain clients.

**Comment by zhuovi** [comment] 2023-02-10 07:39
> > foreach (var client in clients.ToList()) { client.Send(lastest_BID_USDTRY); } It should be that the service is stopped. Please change it to server. Send (last_BID_USDTRY); The server variable is the new NetServer<>object
> 
> But I will not send it to all clients later on. I will send it to certain clients.

When you send it, add a try { client.Send("msg"); } catch {} to try, and it won't stop

**Comment by hasancaktar** [comment] 2023-02-10 07:51
Ok i will try. And I couldn't do this method you mentioned. As you said,  "把你list这个类型换成 System.Collections.Concurrent.ConcurrentBag<XiaoFeng.Net.IServerSession> 这个类型试一下，或者直接用 server.ConnectionSocketList 这个内置列表" I changed the type of client list, but I cannot access the client list. Where am I doing wrong? Can you make a small sample please? Thank you very much, you are really supportive. I am grateful

**Comment by zhuovi** [comment] 2023-02-10 08:10
//新建一个服务端,同时支持websocket,socket客户端连接
var server = new NetServer<ServerSession>(8088)
{
    //是否启用ping
    IsPing = true,
    //是否启用新行
    IsNewLine = true,
    //传输编码
    Encoding = System.Text.Encoding.UTF8,
    //认证 认证不过则直接断开
    SocketAuth = s =>
    {
        //判断 客户端是否符合认证,不符合则直接返回false即可
        return true;
    }
};
server.OnStart += (s, e) =>
{
    //服务端启动事件
    Console.WriteLine($"启动!-{DateTime.Now:yyyy-MM-dd HH:mm:ss.fffffff}");
};
server.OnNewConnection += (s, e) =>
{
    //客户端新连接事件
    Console.WriteLine($"新连接-{DateTime.Now:yyyy-MM-dd HH:mm:ss.fffffff}");
    //给当前客户端设置一个频道名  为后边按频道名发送作准备
    //一个客户端可以订阅多个频道
    //websocket可以从头里面获取标识
    //如果非websocket 可以从消息里设置频道消息
    if (s.Headers.IndexOf("Channel:a") > 0)
        s.AddChannel("a");
    else
        s.AddChannel("b");
};
server.OnDisconnected += (s, e) =>
{
    //客户端断开连接事件
    Console.WriteLine($"断开连接!-{DateTime.Now:yyyy-MM-dd HH:mm:ss.fffffff}");
};
server.OnMessage += (s, m, e) =>
{
    //接收消息事件
    if (m.IndexOf("Channel:a") > 0)
    {
        s.AddChannel("a");
        return;
    }
    else if (m.IndexOf("Channel:b") > 0)
    {
        s.AddChannel("b");
        return;
    }
    Console.WriteLine($"消息-{m}-{DateTime.Now:yyyy-MM-dd HH:mm:ss.fffffff}");
    //把当前消息发送到频道名为a的所有客户端
    server.Send("a", Encoding.UTF8.GetBytes("消息"));
    //回复当前客户端消息
    s.Send("消息");
    //发送消息给所有客户端
    server.Send("消息");
};
server.OnMessageByte += (session, message, e) =>
{
    //接收消息事件
    session.Send("回复客户端消息");
};
server.OnError += (s, e) =>
{
    //服务端出错事件
    Console.WriteLine($"出错-{e.Message}-{DateTime.Now:yyyy-MM-dd HH:mm:ss.fffffff}");
};
server.OnClientError += (session, e) =>
{
    //客户端出错事件
};
server.OnError += (session, e) =>
{
    //服务端出错事件
};
server.OnStop += (socket, e) =>
{
    //服务端停止事件
};
server.Start();
//添加黑名单
server.AddIpBlack("10.10.10.10");
//移除黑名单
server.RemoveIpBlack("10.10.10.10");
//清空黑名单
server.ClearIpBlack();
//断开所有客户端
server.ClearQueue();
//在线客户端列表 复制出来的
var clients = server.GetData();
//在线客户端列表 原列表
var clients1 = server.ConnectionSocketList;

**Comment by hasancaktar** [comment] 2023-02-28 12:29
I get the error in the picture and the server is down. I searched for the reason but couldn't find it. Can you help with this error?
![Ekran görüntüsü 2023-02-28 142559](https://user-images.githubusercontent.com/53625738/221854461-73abc6ff-90d8-4e01-8892-09e533e5a847.png)

**Comment by zhuovi** [comment] 2023-03-01 00:54
> I get the error in the picture and the server is down. I searched for the reason but couldn't find it. Can you help with this error? ![Ekran görüntüsü 2023-02-28 142559](https://user-images.githubusercontent.com/53625738/221854461-73abc6ff-90d8-4e01-8892-09e533e5a847.png)

This error means that your client object has been disconnected and released, and you have to operate it again. You should judge whether the connection has been disconnected or released when operating it.

**Comment by hasancaktar** [comment] 2023-03-01 07:07
I'm talking about this error. When it gives the error in this picture, the server shuts down completely and I couldn't find where it came from. Why is it giving an error saying "Operation completed successfully"?
![Ekran görüntüsü 2023-02-28 142559](https://user-images.githubusercontent.com/53625738/222068273-b42291c5-7737-4cb1-bd9c-c0fac481913b.png)

**Comment by hasancaktar** [comment] 2023-03-01 12:44
> I'm talking about this error. When it gives the error in this picture, the server shuts down completely and I couldn't find where it came from. Why is it giving an error saying "Operation completed successfully"? ![Ekran görüntüsü 2023-02-28 142559](https://user-images.githubusercontent.com/53625738/222068273-b42291c5-7737-4cb1-bd9c-c0fac481913b.png)

@zhuovi  did you find a solution

**Comment by hasancaktar** [comment] 2023-03-02 08:19
@zhuovi My guess about the cause of the error is the version. I think this error started to appear after upgrading the version to 3.3.3 I couldn't find any other information. If you need any other information, you can ask for it.

**Comment by zhuovi** [comment] 2023-03-02 10:56
> @zhuovi My guess about the cause of the error is the version. I think this error started to appear after upgrading the version to 3.3.3 I couldn't find any other information. If you need any other information, you can ask for it.

Don't worry about this error. It is when the server is closed, I will record this error exception, in order to know that the connection is closed by the server and cancel all threads waiting to receive messages when troubleshooting problems later.

**Comment by zhuovi** [comment] 2023-03-02 10:58
![image](https://user-images.githubusercontent.com/16105174/222409657-cf7b4ce7-30d2-4ba4-a163-7c476f61077d.png)

**Closed** 2023-03-02 11:11 UTC
